
'use client'

import { useState } from 'react'
import { motion } from 'framer-motion'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Badge } from '@/components/ui/badge'
import { Eye, Sparkles, Copy, Share2, Download, RotateCcw } from 'lucide-react'
import Image from 'next/image'
import { OracleCard } from '@/lib/oracle-cards'

interface OracleReadingProps {
  card: OracleCard
  personalizedMessage: string
  spookyInsight: string
  userName: string
  onNewReading: () => void
}

export default function OracleReading({ 
  card, 
  personalizedMessage, 
  spookyInsight, 
  userName,
  onNewReading 
}: OracleReadingProps) {
  const [showInsight, setShowInsight] = useState(false)
  const [copied, setCopied] = useState(false)
  const [unlockMethod, setUnlockMethod] = useState<'share' | 'subscribe' | null>(null)

  const copyReading = async () => {
    const readingText = `
${card.title} - ${card.name}

${personalizedMessage}

${card.meaning}

Cosmic Keywords: ${card.keywords.join(', ')}

✨ Generated by 3I/Atlas Oracle - https://3iatlas.com
    `.trim()

    try {
      await navigator.clipboard.writeText(readingText)
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    } catch (err) {
      console.error('Failed to copy:', err)
    }
  }

  const shareReading = async () => {
    const shareText = `🔮 Just got my 3I/Atlas Oracle reading: "${card.title} - ${card.name}"\n\n"${personalizedMessage}"\n\nGet your cosmic reading at https://3iatlas.com/#oracle ✨`
    
    if (navigator.share) {
      try {
        await navigator.share({
          title: `${card.title} - 3I/Atlas Oracle Reading`,
          text: shareText,
          url: window.location.href + '#oracle'
        })
        setUnlockMethod('share')
        setTimeout(() => setShowInsight(true), 1000)
      } catch (err) {
        console.error('Failed to share:', err)
        // Fallback to copying
        await copyShareText(shareText)
      }
    } else {
      await copyShareText(shareText)
    }
  }

  const copyShareText = async (text: string) => {
    try {
      await navigator.clipboard.writeText(text)
      alert('✨ Reading copied to clipboard! Share it anywhere to unlock your deeper insight!')
      setUnlockMethod('share')
      setTimeout(() => setShowInsight(true), 1000)
    } catch (err) {
      console.error('Failed to copy:', err)
    }
  }

  const subscribeToUnlock = () => {
    window.open('https://mysticarcana.com/signup?utm_source=3iatlas&oracle_unlock=true', '_blank')
    setUnlockMethod('subscribe')
    setTimeout(() => setShowInsight(true), 2000)
  }

  return (
    <div className="max-w-2xl mx-auto">
      <motion.div
        initial={{ opacity: 0, scale: 0.9 }}
        animate={{ opacity: 1, scale: 1 }}
        transition={{ duration: 0.8 }}
      >
        <Card className="bg-black/90 border border-purple-500/50 backdrop-blur-md overflow-hidden">
          {/* Card Header */}
          <CardHeader className="text-center pb-4 bg-gradient-to-b from-purple-900/20 to-transparent">
            <div className="flex items-center justify-center space-x-2 mb-4">
              <Badge className="bg-purple-500/20 text-purple-300 border-purple-400 px-3 py-1">
                PREVIEW MODE
              </Badge>
            </div>
            <CardTitle className="text-2xl md:text-3xl font-bold bg-gradient-to-r from-purple-400 to-cyan-400 bg-clip-text text-transparent">
              {card.title}
            </CardTitle>
            <p className="text-lg text-cyan-300 font-medium">
              {card.name}
            </p>
          </CardHeader>

          <CardContent className="space-y-6">
            {/* Card Image */}
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.8, delay: 0.2 }}
              className="relative h-64 md:h-80 rounded-lg overflow-hidden border border-purple-500/30"
            >
              <Image
                src={card.image}
                alt={card.name}
                fill
                className="object-cover"
              />
              <div className="absolute inset-0 bg-gradient-to-t from-black/60 via-transparent to-transparent" />
              <div className="absolute bottom-4 left-4">
                <div className="flex space-x-1">
                  {card.keywords.slice(0, 3).map((keyword, i) => (
                    <Badge 
                      key={keyword}
                      className="bg-black/60 text-purple-300 border-purple-400/30 text-xs"
                    >
                      {keyword}
                    </Badge>
                  ))}
                </div>
              </div>
            </motion.div>

            {/* Personalized Message */}
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.8, delay: 0.4 }}
              className="bg-gradient-to-r from-purple-900/20 to-cyan-900/20 p-6 rounded-lg border border-purple-500/20"
            >
              <div className="flex items-center space-x-2 mb-4">
                <Eye className="h-5 w-5 text-purple-400" />
                <h3 className="text-lg font-semibold text-white">
                  Personal Oracle Message for {userName}
                </h3>
              </div>
              <p className="text-gray-200 leading-relaxed text-lg italic">
                "{personalizedMessage}"
              </p>
            </motion.div>

            {/* Universal Meaning */}
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.8, delay: 0.6 }}
              className="space-y-4"
            >
              <h3 className="text-xl font-semibold text-white flex items-center">
                <Sparkles className="h-5 w-5 text-cyan-400 mr-2" />
                Universal Meaning
              </h3>
              <p className="text-gray-300 leading-relaxed">
                {card.meaning}
              </p>
            </motion.div>

            {/* Cosmic Keywords */}
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.8, delay: 0.8 }}
              className="space-y-3"
            >
              <h4 className="text-lg font-semibold text-white">Cosmic Keywords</h4>
              <div className="flex flex-wrap gap-2">
                {card.keywords.map(keyword => (
                  <Badge 
                    key={keyword}
                    className="bg-gradient-to-r from-purple-500/20 to-cyan-500/20 text-purple-300 border-purple-400/30"
                  >
                    {keyword}
                  </Badge>
                ))}
              </div>
            </motion.div>

            {/* Spooky Insight - Locked Behind Actions */}
            {!showInsight ? (
              <motion.div
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.8, delay: 1.0 }}
                className="text-center space-y-4"
              >
                <div className="bg-gradient-to-r from-red-900/30 to-purple-900/30 p-6 rounded-lg border border-red-500/30">
                  <Eye className="h-8 w-8 text-red-400 animate-pulse mx-auto mb-4" />
                  <h3 className="text-xl font-bold text-red-300 mb-2">
                    🔒 Deeper Oracle Vision Available
                  </h3>
                  <p className="text-red-200 mb-6">
                    The Oracle sees something profound about your soul's mission, but this vision requires cosmic exchange...
                  </p>
                  
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                    <Button
                      onClick={shareReading}
                      className="bg-gradient-to-r from-purple-600 to-pink-600 hover:from-purple-700 hover:to-pink-700 text-white font-medium"
                    >
                      <Share2 className="mr-2 h-4 w-4" />
                      Share Reading to Unlock
                    </Button>
                    
                    <Button
                      onClick={subscribeToUnlock}
                      className="bg-gradient-to-r from-cyan-600 to-blue-600 hover:from-cyan-700 hover:to-blue-700 text-white font-medium"
                    >
                      <Sparkles className="mr-2 h-4 w-4" />
                      Subscribe to Mystic Arcana
                    </Button>
                  </div>
                  
                  <p className="text-xs text-red-400/70 mt-4">
                    The Oracle's deepest visions require energetic reciprocity
                  </p>
                </div>
              </motion.div>
            ) : (
              <motion.div
                initial={{ opacity: 0, scale: 0.9 }}
                animate={{ opacity: 1, scale: 1 }}
                transition={{ duration: 0.6 }}
                className="bg-gradient-to-br from-red-900/30 to-purple-900/30 border border-red-500/50 p-6 rounded-lg"
              >
                <div className="flex items-center justify-between mb-4">
                  <div className="flex items-center space-x-2">
                    <Eye className="h-5 w-5 text-red-400 animate-pulse" />
                    <h3 className="text-lg font-semibold text-red-300">
                      🔓 Deeper Oracle Vision Unlocked
                    </h3>
                  </div>
                  {unlockMethod && (
                    <div className="text-xs text-green-400 bg-green-900/30 px-2 py-1 rounded">
                      {unlockMethod === 'share' ? '✨ Via Sharing' : '🌟 Via Subscription'}
                    </div>
                  )}
                </div>
                <div className="bg-black/30 p-4 rounded border-l-4 border-red-500">
                  <p className="text-red-200 italic text-lg leading-relaxed">
                    "{spookyInsight}"
                  </p>
                </div>
                <p className="text-xs text-red-400/70 mt-3 text-center">
                  ⚡ The Oracle's sight penetrates all dimensions of your existence ⚡
                </p>
              </motion.div>
            )}

            {/* Action Buttons */}
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.8, delay: 1.2 }}
              className="flex flex-wrap gap-3 justify-center pt-6 border-t border-gray-700"
            >
              <Button
                onClick={copyReading}
                variant="outline"
                className="border-purple-500 text-purple-400 hover:bg-purple-500 hover:text-white"
              >
                <Copy className="mr-2 h-4 w-4" />
                {copied ? 'Copied!' : 'Copy Reading'}
              </Button>
              <Button
                onClick={shareReading}
                variant="outline"
                className="border-cyan-500 text-cyan-400 hover:bg-cyan-500 hover:text-white"
              >
                <Share2 className="mr-2 h-4 w-4" />
                Share
              </Button>
              <Button
                onClick={onNewReading}
                className="bg-gradient-to-r from-purple-500 to-cyan-500 hover:from-purple-600 hover:to-cyan-600"
              >
                <RotateCcw className="mr-2 h-4 w-4" />
                New Reading
              </Button>
            </motion.div>

            {/* Preview Mode Notice */}
            <div className="text-center text-xs text-gray-500 pt-4 border-t border-gray-800">
              <p>🚀 Preview Mode - Full oracle features coming soon!</p>
              <p className="mt-1">
                Subscribe above to be notified when the complete 44-card deck launches
              </p>
            </div>
          </CardContent>
        </Card>
      </motion.div>
    </div>
  )
}
